### ISSUE TITLE
UI - Templates

### ISSUE THREAD

**Issue by olewoy** [hpi-swa-teaching/SpotifyConnect#10]
As a user I want to have a intuitive UI, where I am able to find all features fast.

- [x] Button Template as abstract class
       - Text Button
       - Icon Button
- [x] SPOCApp with instance handling
       - SPOCComponent abstract class for handling auth access
       - Open SPOCApp with Squeak Topbar

**Comment by ronjakrg** [comment]
Spotify Design Guidelines https://developer.spotify.com/documentation/design
