### ISSUE TITLE
Searchbar for playlists

### ISSUE THREAD

**Issue by tanja04** [hpi-swa-teaching/SpotifyConnect#14]
As a music listener I want to search playlists in a search bar to find new music related to a topic.

- [x] style guidelines
- [x] integration with search results: list of playlist and its creator/owner
- [x] top 10, opt. more
- [x] ability to select a playlist to see its contents

**Comment by vincenteichhorn** [comment]
siehe Searchbar wiht filters

**Comment by vincenteichhorn** [comment]
siehe Searchbar wiht filters
