### ISSUE TITLE
Refactoring Update Playback State

### ISSUE THREAD

**Issue by olewoy** [hpi-swa-teaching/SpotifyConnect#31]
As a SWA chair we want to have well structured code in order to better understand it.

- [x] general method for updating playback state
- [x] update all components when changing anything concerning playback state

![PXL_20240610_150221351](https://github.com/hpi-swa-teaching/SpotifyConnect/assets/24360071/10adf275-fd67-465f-8172-acad4f817ee8)

**Comment by tanja04** [comment]
problem:
updating with old values, e.g.
- playPauseIcon and currentlyPlaying after clicking a player button
- volume slider after using it (sometimes)
